#!/bin/bash
exit
cd $(dirname $0)
eclair_onchain=$($MAINNET_ECLAIR onchainbalance | jq  '.confirmed | tonumber | . / 100000 | floor ')
lnd_onchain=$($MAINNET_LNCLI walletbalance | jq '.total_balance   | tonumber | . / 100000 | floor ')

if (( "$lnd_onchain < 900" )); then
    amount=100
    if (( "$eclair_onchain > $amount" )); then
	echo "rebalance_onchain: $amount mBTC"
	amount_sat=$amount"00000"
	addr=$($MAINNET_LNCLI newaddress p2wkh|jq -r .address)
	$MAINNET_ECLAIR sendonchain --address=$addr --amountSatoshis=$amount_sat --confirmationTarget=6
    else
	echo "rebalance_onchain: not enough funds"
    fi
else
    echo "rebalance_onchain: nothing to do"
fi
