#!/bin/bash
cd $(dirname $0)
eclair_local=$(./view_eclair_swapserver | jq '.to_local | tonumber | floor')
if (( "$eclair_local < 150" )); then
    echo "rebalance_offchain: 100 mBTC "
    ./send_swapserver_to_eclair 100
elif (( "$eclair_local > 350" )); then
    echo "rebalance_offchain: 100 mBTC "
    ./send_eclair_to_swapserver 100
fi
