#!/bin/bash
cd $(dirname $0)
eclair_local=$(./view_eclair_lnd | jq '.to_local | tonumber | floor')
if (( "$eclair_local < 200" )); then
    echo "rebalance_offchain: 50 mBTC "
    ./send_lnd_to_eclair 50
else
    echo "rebalance_offchain: nothing to do"
fi
