#!/bin/bash
echo "Send amount: $1mBTC"
amount_sat=$1"00000"
addr=$($MAINNET_LNCLI newaddress p2wkh|jq -r .address)
$MAINNET_ECLAIR sendonchain --address=$addr --amountSatoshis=$amount_sat --confirmationTarget=6
