#!/bin/bash

NET="$1"
usage="usage: $0 (testnet|mainnet)"

if [[ -n "$1" && ( "$1" == "mainnet" || "$1" == "testnet" ) ]] ; then

    /opt/bitcoin/bin/bitcoind -conf="/home/boltz/$NET/bitcoin.conf" &

else
    echo $usage
    exit 1
fi
